//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ue_JLI_SLItemsExt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ue_JLI_SLItemsExt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare 
        ///  @Item								ItemType	= &apos;{0}&apos;
        ///, @PropertyName						varchar(30) = &apos;{1}&apos;
        ///, @ReasonDate						datetime	= &apos;{2}&apos;
        ///, @inpNewStatus						nchar(1)	= &apos;{3}&apos;
        ///, @inpOldStatus						nchar(1)	= &apos;{4}&apos;
        ///, @inpNewItemLifeCycleStatus		varchar(30)	= &apos;{5}&apos;
        ///, @inpOldItemLifeCycleStatus		varchar(30)	= &apos;{6}&apos;
        ///, @inpNewSchedItemType				varchar(30)	= &apos;{8}&apos;
        ///, @inpOldSchedItemType				varchar(30)	= &apos;{9}&apos;
        ///
        ///
        ///
        ///Declare @DroppedDate		DateType
        ///Select @DroppedDate = IsNull(@ReasonDate,GETDATE())
        ///
        ///Declare @ResultSet Tabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_ItemAcsseDataInsertAndUpdate {
            get {
                return ResourceManager.GetString("ue_JLI_ItemAcsseDataInsertAndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare 
        ///  @Item								ItemType	= &apos;{0}&apos;
        ///, @PropertyName						varchar(30) = &apos;{1}&apos;
        ///, @ReasonDate						datetime	= &apos;{2}&apos;
        ///, @inpNewStatus						nchar(1)	= &apos;{3}&apos;
        ///, @inpOldStatus						nchar(1)	= &apos;{4}&apos;
        ///, @inpNewItemLifeCycleStatus		varchar(30)	= &apos;{5}&apos;
        ///, @inpOldItemLifeCycleStatus		varchar(30)	= &apos;{6}&apos;
        ///
        ///
        ///
        ///Declare @DroppedDate		DateType
        ///Select @DroppedDate = IsNull(@ReasonDate,GETDATE())
        ///
        ///Declare @ResultSet Table(
        /// Record_Type			nchar(1)
        ///,Item					ItemType
        ///,CollecStatus			nchar(1)
        ///,CollecDroppedDate	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_ItemCollecDataUpdate {
            get {
                return ResourceManager.GetString("ue_JLI_ItemCollecDataUpdate", resourceCulture);
            }
        }
    }
}
