//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ue_JLI_EDIFileDrop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ue_JLI_EDIFileDrop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Declare  @InvNum InvNumType = &apos;1&apos; 
        ///Select @InvNum = dbo.ExpandKyByType(&apos;InvNumType&apos;, @InvNum)
        ///Update [dbo].[artran] set Uf_EDIInv_sendDate = @InvSendDate Where type=&apos;I&apos; AND inv_num = @InvNum
        ///.
        /// </summary>
        internal static string ue_JLI_ARPostedTranDtlEDIInvSentDateUpdate {
            get {
                return ResourceManager.GetString("ue_JLI_ARPostedTranDtlEDIInvSentDateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Accept&quot;,
        ///    &quot;Type&quot;: &quot;header&quot;,
        ///    &quot;Value&quot;: &quot;application/json&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;body&quot;,
        ///    &quot;Type&quot;: &quot;body&quot;,
        ///    &quot;Value&quot;: {
        ///      &quot;item&quot;: {
        ///        &quot;attrs&quot;: {
        ///          &quot;attr&quot;: [
        ///            {
        ///              &quot;name&quot;: &quot;{0}&quot;,
        ///              &quot;value&quot;: &quot;{1}&quot;
        ///            }
        ///          ]
        ///        }
        ///      },
        ///      &quot;files&quot;: {
        ///        &quot;res&quot;: [
        ///          {
        ///            &quot;filename&quot;: &quot;{2}&quot;,
        ///            &quot;base64&quot;: &quot;{3}&quot;
        ///          }
        ///        ]
        ///      },
        ///      &quot;acl&quot;: {
        ///        &quot;name&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_Json {
            get {
                return ResourceManager.GetString("ue_JLI_Json", resourceCulture);
            }
        }
    }
}
