//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ue_JLI_PBI_DataShare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ue_JLI_PBI_DataShare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    LH.CustNum,
        ///    COUNT(DISTINCT LH.LoadNo) AS [LoadCount],
        ///    CAST(SUM(LI.loadqty) AS INT) AS [Pcs],
        ///    SUM(LI.loadqty * CI.price_conv) AS [LoadValue],
        ///    CA.name AS CustomerName
        ///FROM ue_JLI_LoadHdr LH
        ///JOIN ue_JLI_LoadItem LI 
        ///    ON LI.LoadNo = LH.LoadNo
        ///JOIN coitem_mst CI 
        ///    ON CI.co_num = LI.CO_Num 
        ///   AND CI.co_line = LI.CO_Line
        ///LEFT JOIN custaddr_mst CA 
        ///    ON LH.CustNum = CA.cust_num 
        ///   AND CA.cust_seq = 0
        ///WHERE LH.LoadType NOT IN (&apos;Part&apos;, &apos;Mult&apos;)
        ///  AND CONVERT(date,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_PBI_CLM_DailyShipByCustNum {
            get {
                return ResourceManager.GetString("ue_JLI_PBI_CLM_DailyShipByCustNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	LH.Whse,
        ///    COUNT(DISTINCT LH.LoadNo) AS [LoadCount],
        ///    CAST(SUM(LI.loadqty) AS INT) AS [Pcs],
        ///    SUM(LI.loadqty * CI.price_conv) AS [LoadValue]
        ///FROM ue_JLI_LoadHdr LH
        ///JOIN ue_JLI_LoadItem LI 
        ///    ON LI.LoadNo = LH.LoadNo
        ///JOIN coitem_mst CI 
        ///    ON CI.co_num = LI.CO_Num 
        ///   AND CI.co_line = LI.CO_Line
        ///LEFT JOIN custaddr_mst CA 
        ///    ON LH.CustNum = CA.cust_num 
        ///   AND CA.cust_seq = 0
        ///WHERE LH.LoadType NOT IN (&apos;Part&apos;, &apos;Mult&apos;)
        ///  AND CONVERT(date, LH.shippeddate) = @ShippedDate
        ///GROU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_PBI_CLM_DailyShipByWhse {
            get {
                return ResourceManager.GetString("ue_JLI_PBI_CLM_DailyShipByWhse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH Base AS (
        ///    SELECT
        ///        LEFT(LH.Whse, 2) AS Whse,
        ///        LH.LoadNo,
        ///        LI.loadqty,
        ///        LI.loadqty * CI.price_conv AS LoadValue,
        ///        LH.ShippedDate
        ///    FROM ue_JLI_LoadHdr LH
        ///    INNER JOIN ue_JLI_LoadItem LI ON LI.LoadNo = LH.LoadNo
        ///    INNER JOIN coitem_mst CI ON CI.co_num = LI.CO_Num AND CI.co_line = LI.CO_Line
        ///    LEFT JOIN custaddr_mst CA ON LH.CustNum = CA.cust_num AND CA.cust_seq = 0
        ///    WHERE LH.LoadType NOT IN (&apos;Part&apos;, &apos;Mult&apos;)
        ///	  AND MONTH(ShippedDate) = MONTH(@Sh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_PBI_CLM_DailyShipSummary {
            get {
                return ResourceManager.GetString("ue_JLI_PBI_CLM_DailyShipSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--CREATE Proc [dbo].[JLI_JobMatlUsageByShipToSp]
        ///--As
        ///Begin
        ///------------------------------------------------------------------------------------------------------
        ///--****
        ///--Truncate Table JLI_JobMatlUsageByShipTo_mst
        ///--****
        ///
        ///Insert Into ue_JLI_JobMatlUsageByShipTo(item
        ///								,month
        ///								,year								
        ///								,cust_num
        ///								,cust_seq
        ///								,total_qty
        ///								,co_num
        ///								,co_line) 
        ///								Select jm.item
        ///		                              ,DATENAME(Month,jm.CreateDate) As Month
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_PBI_JobMatlUsageByShipTo {
            get {
                return ResourceManager.GetString("ue_JLI_PBI_JobMatlUsageByShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--CREATE Proc [dbo].[JLI_planningdetailsSp](@ProductCode		nvarchar(20) = Null)
        ///--As
        ///Begin
        ///
        ///	--DECLARE @Site SiteType
        ///	--	   ,@Session RowPointertype = NEWID()
        ///	   
        ///	--SELECT @Site = site FROM parms_mst
        ///
        ///	--EXEC dbo.InitSessionContextSp
        ///	--  @ContextName = &apos;ContextNameSp&apos;
        ///	--, @SessionID   = @Session
        ///	--, @Site        = @Site
        ///
        ///   	Declare @planningdetailsTable Table(   
        ///	  Item				ItemType
        ///	, OrigQty			decimal(25,10)
        ///	, DueDate			DateTimeType
        ///	, RefNum			Varchar(50)
        ///	, OrdType			Varchar( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_PBI_PlanningDetail {
            get {
                return ResourceManager.GetString("ue_JLI_PBI_PlanningDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --CREATE PROCEDURE [dbo].[JLI_planningdetailsSp_BGTaskSubmitSp]
        ///--AS
        ///Begin
        /// 
        ///	--Exec SetSiteSp &apos;JLI&apos;,Null
        ///	declare   
        ///	@Severity			int
        ///	, @BGTaskName		BGTaskNameType
        ///	, @BGTaskParms		BGTaskParmsType
        ///	, @BGTaskID			TokenType
        ///	, @UserName			UserNameType 
        ///	, @Infobar			InfobarType 
        ///
        ///	------------------------------------
        ///	--Truncate Table ue_JLI_planningdetails
        ///	Delete From ue_JLI_planningdetails
        ///	--------------------------------
        ///	--Task Parameters will use the Preferred Input Settings.
        ///	selec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_PBI_PlanningDetail_BGTaskSubmit {
            get {
                return ResourceManager.GetString("ue_JLI_PBI_PlanningDetail_BGTaskSubmit", resourceCulture);
            }
        }
    }
}
