//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ue_JLI_PBI_DataShare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ue_JLI_PBI_DataShare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    LH.CustNum,
        ///    COUNT(DISTINCT LH.LoadNo) AS [LoadCount],
        ///    CAST(SUM(LI.loadqty) AS INT) AS [Pcs],
        ///    SUM(LI.loadqty * CI.price_conv) AS [LoadValue],
        ///    CA.name AS CustomerName
        ///FROM ue_JLI_LoadHdr LH
        ///JOIN ue_JLI_LoadItem LI 
        ///    ON LI.LoadNo = LH.LoadNo
        ///JOIN coitem_mst CI 
        ///    ON CI.co_num = LI.CO_Num 
        ///   AND CI.co_line = LI.CO_Line
        ///LEFT JOIN custaddr_mst CA 
        ///    ON LH.CustNum = CA.cust_num 
        ///   AND CA.cust_seq = 0
        ///WHERE LH.LoadType NOT IN (&apos;Part&apos;, &apos;Mult&apos;)
        ///  AND CONVERT(date,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_PBI_CLM_DailyShipByCustNum {
            get {
                return ResourceManager.GetString("ue_JLI_PBI_CLM_DailyShipByCustNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	LH.Whse,
        ///    COUNT(DISTINCT LH.LoadNo) AS [LoadCount],
        ///    CAST(SUM(LI.loadqty) AS INT) AS [Pcs],
        ///    SUM(LI.loadqty * CI.price_conv) AS [LoadValue]
        ///FROM ue_JLI_LoadHdr LH
        ///JOIN ue_JLI_LoadItem LI 
        ///    ON LI.LoadNo = LH.LoadNo
        ///JOIN coitem_mst CI 
        ///    ON CI.co_num = LI.CO_Num 
        ///   AND CI.co_line = LI.CO_Line
        ///LEFT JOIN custaddr_mst CA 
        ///    ON LH.CustNum = CA.cust_num 
        ///   AND CA.cust_seq = 0
        ///WHERE LH.LoadType NOT IN (&apos;Part&apos;, &apos;Mult&apos;)
        ///  AND CONVERT(date, LH.shippeddate) = @ShippedDate
        ///GROU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_PBI_CLM_DailyShipByWhse {
            get {
                return ResourceManager.GetString("ue_JLI_PBI_CLM_DailyShipByWhse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH Base AS (
        ///    SELECT
        ///        LEFT(LH.Whse, 2) AS Whse,
        ///        LH.LoadNo,
        ///        LI.loadqty,
        ///        LI.loadqty * CI.price_conv AS LoadValue,
        ///        LH.ShippedDate
        ///    FROM ue_JLI_LoadHdr LH
        ///    INNER JOIN ue_JLI_LoadItem LI ON LI.LoadNo = LH.LoadNo
        ///    INNER JOIN coitem_mst CI ON CI.co_num = LI.CO_Num AND CI.co_line = LI.CO_Line
        ///    LEFT JOIN custaddr_mst CA ON LH.CustNum = CA.cust_num AND CA.cust_seq = 0
        ///    WHERE LH.LoadType NOT IN (&apos;Part&apos;, &apos;Mult&apos;)
        ///	  AND MONTH(ShippedDate) = MONTH(@Sh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_PBI_CLM_DailyShipSummary {
            get {
                return ResourceManager.GetString("ue_JLI_PBI_CLM_DailyShipSummary", resourceCulture);
            }
        }
    }
}
