//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLI_JPScans.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JLI_JPScans.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Declare
        ///     @IsGroup		ListYesNoType		= &apos;{inpIsGroup}&apos;
        ///	,@SessionID		Uniqueidentifier	= &apos;{inpSessionID}&apos;
        ///	,@emp_num		EmpNumType			= &apos;{inpEmpNum}&apos;
        ///	,@work_date		DateType			= &apos;{inpWorkDate}&apos;
        ///	,@TimeType		nchar(10)			= &apos;{inpTimeType}&apos;
        ///	,@TimeQty		int					= {inpTimeQty}
        ///	,@TimeDesc		nvarchar(100)		= &apos;{inpTimeDesc}&apos;
        ///
        ///BEGIN
        ///
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///    declare @err         int
        ///	       ,@EmpCount    int
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JLI_JPScan_Txt {
            get {
                return ResourceManager.GetString("JLI_JPScan.Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare
        ///     @IsGroup    ListYesNoType    = &apos;{0}&apos;
        ///	,@SessionID  Uniqueidentifier = &apos;{1}&apos;
        ///	,@emp_num    EmpNumType       = &apos;{2}&apos;
        ///	,@work_date  DateType         = &apos;{3}&apos;
        ///	,@OtherRate  decimal(9,2)     = {4}
        ///	,@OtherQty   int              = {5}
        ///	,@OtherDesc  nvarchar(100)    = &apos;{6}&apos;
        ///
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///    declare @err         int
        ///	       ,@EmpCount    int
        ///		   ,@actual_rate decimal(9,2)
        ///		   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_SaveOtherScan {
            get {
                return ResourceManager.GetString("ue_JLI_SaveOtherScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare
        /// @IsGroup   ListYesNoType    = {0}
        ///,@SessionID Uniqueidentifier = &apos;{1}&apos;
        ///,@emp_num   EmpNumType       = &apos;{2}&apos;
        ///,@work_date DateType         = &apos;{3}&apos;
        ///,@ScanData  nvarchar(100)    = &apos;{4}&apos;
        ///
        ///
        ///
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///    declare @err            int
        ///	       ,@EmpCount       int
        ///		   ,@actual_rate    decimal(9,2)
        ///		   ,@scan_date      datetime
        ///		   ,@scan_by        EmpNumType
        ///		   ,@item      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_SavePieceScan {
            get {
                return ResourceManager.GetString("ue_JLI_SavePieceScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare
        ///     @IsGroup		ListYesNoType		= &apos;{0}&apos;
        ///	,@SessionID		Uniqueidentifier	= &apos;{1}&apos;
        ///	,@emp_num		EmpNumType			= &apos;{2}&apos;
        ///	,@work_date		DateType			= &apos;{3}&apos;
        ///	,@TimeType		nchar(10)			= &apos;{4}&apos;
        ///	,@TimeQty		int					= {5}
        ///	,@TimeDesc		nvarchar(100)		= &apos;{6}&apos;
        ///
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///    declare @err         int
        ///	       ,@EmpCount    int
        ///		   ,@actual_rate decimal(9,2)
        ///		   ,@scan_date   datetime
        ///		   ,@sc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_SaveTimeScan {
            get {
                return ResourceManager.GetString("ue_JLI_SaveTimeScan", resourceCulture);
            }
        }
    }
}
