//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ue_JLI_ItemAvailabilityDashboard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ue_JLI_ItemAvailabilityDashboard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare
        ///  @custNum			CustNumType		= &apos;{0}&apos; 
        ///, @item				ItemType		= &apos;{1}&apos;
        ///
        ///
        ///Declare @Job				JobType
        ///	,@Suffix				SuffixType
        ///	,@cust_item				CustItemType
        ///	,@accessory				ItemType
        ///	,@fab_comp_item			ItemType
        ///	,@description			DescriptionType
        ///	,@req_qty				QtyPerType
        ///	,@avail_qty				QtyPerType
        ///	,@po_qty				QtyPerType
        ///	,@po_due_date			DateType
        ///	,@avail_qty_to_order	QtyPerType
        ///	,@avail_date			DateType
        ///
        ///	,@matl_qty_conv			QtyPerType
        ///	,@qty					Int
        ///	,@QtyOnHand				QtyPerType
        ///	,@firm					QtyPerTyp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_CLM_ItemAvailabilityDashboard {
            get {
                return ResourceManager.GetString("ue_JLI_CLM_ItemAvailabilityDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///	Declare
        ///  @custNum			CustNumType		= &apos;{0}&apos; 
        ///, @item				ItemType		= &apos;{1}&apos;
        ///
        ///
        ///Declare @Job				JobType
        ///	,@Suffix				SuffixType
        ///	,@cust_item				CustItemType
        ///	,@accessory				ItemType
        ///	,@fab_comp_item			ItemType
        ///	,@description			DescriptionType
        ///	,@req_qty				QtyPerType
        ///	,@avail_qty				QtyPerType
        ///	,@po_qty				QtyPerType
        ///	,@po_due_date			DateType
        ///	,@avail_qty_to_order	QtyPerType
        ///	,@avail_date			DateType
        ///
        ///	,@matl_qty_conv			QtyPerType
        ///	,@qty					Int
        ///	,@QtyOnHand				QtyPerType
        ///	,@firm					 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_CLM_ItemAvailabilityDashboard2 {
            get {
                return ResourceManager.GetString("ue_JLI_CLM_ItemAvailabilityDashboard2", resourceCulture);
            }
        }
    }
}
