//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ue_JLI_AvailCollecGroups.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ue_JLI_AvailCollecGroups.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare 
        ///  @inpCustNum					CustNumType		= &apos;{0}&apos;
        ///, @inpCollectionGroup			nvarchar(30)	= &apos;{1}&apos;
        ///
        ///Delete From ue_JLI_AvailableCollection_mst Where cust_num = @inpCustNum And CollectionGroup = @inpCollectionGroup And record_type = &apos;C&apos;
        ///
        ///If @inpCollectionGroup = &apos;Accessories&apos;
        ///Begin
        ///	Delete From ue_JLI_AvailableCollection_mst Where cust_num = @inpCustNum And record_type = &apos;A&apos;
        ///End.
        /// </summary>
        internal static string ue_JLI_AvailCollDataDelete {
            get {
                return ResourceManager.GetString("ue_JLI_AvailCollDataDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Declare 
        ///  @inpCustNum					CustNumType		= &apos;{0}&apos;
        ///, @inpCollectionGroup			nvarchar(30)	= &apos;{1}&apos;
        ///
        ///Declare 
        ///  @ShowCollection				ListYesNoType = 1
        ///, @PriceBook		            ListYesNoType	
        ///, @ContractOnlyCust		        ListYesNoType
        ///
        ///
        ///Declare @ResultSet Table(
        ///  CustNum					Nvarchar(20)
        ///, Item						Nvarchar(30)
        ///, ShowCollection			ListYesNoType
        ///, RecordType				Nchar(1)
        ///, CollectionGroup			Nvarchar(30)
        ///)
        ///
        ///Select @PriceBook = IsNull(Uf_PriceBook,0),@ContractOnlyCust = IsNull(Uf_contract_only_cus [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_AvailCollDataInsertAndDelete {
            get {
                return ResourceManager.GetString("ue_JLI_AvailCollDataInsertAndDelete", resourceCulture);
            }
        }
    }
}
