//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLI_CustomerLineups.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JLI_CustomerLineups.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare
        ///@CustNum		CustNumType,
        ///@Item			ItemType,
        ///@CustItemSeq	CustItemSeqType,
        ///@PriceBook		ListYesNoType
        ///
        ///If IsNull(@PriceBook,&apos;&apos;) = 1
        ///Begin
        ///	SELECT FabricGrade, Price, CAST(EffectDate AS Date) AS EffectDate
        ///	FROM (
        ///		SELECT fabric_grade, CAST(effect_date AS Date) AS effect_date, price,
        ///			   ROW_NUMBER() OVER(PARTITION BY fabric_grade ORDER BY CAST(effect_date AS Date) DESC) rn
        ///		FROM ue_JLI_CustItemFabricPrc
        ///		WHERE cust_num = @CustNum AND item = @Item AND cust_item_seq = @CustItemSeq
        ///	) A
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JLI_GetFabGradePriceInfo {
            get {
                return ResourceManager.GetString("JLI_GetFabGradePriceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Declare @Item			ItemType
        ///
        ///--Select @Item = &apos;S036730XXX-AMMS01&apos;
        ///
        ///SELECT Accessory, OptionItem, item.description AS OptionItemDesc, Qty
        ///FROM JLI_ItemAccessory IA
        ///LEFT JOIN item_mst item
        ///ON item.item = IA.OptionItem
        ///WHERE (Accessory IN (&apos;BASE FABRIC&apos;,&apos;NAIL HEAD&apos;,&apos;CONTRAST WELT&apos;) 
        ///OR (LEFT(Accessory, 1) = &apos;P&apos; AND Accessory &lt;&gt; &apos;PARTS&apos;))
        ///AND IA.item = @Item.
        /// </summary>
        internal static string JLI_getItemAccessoriesInfo {
            get {
                return ResourceManager.GetString("JLI_getItemAccessoriesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare 
        ///  @CustNum			CustNumType
        ///, @Item				ItemType
        ///
        ///--Select @CustNum = &apos;C001537&apos;,@Item = &apos;S036730XXX-AMMS01&apos;
        ///
        ///If Exists(Select * From ue_JLI_AvailableCollection_mst Where cust_num = @CustNum And item = @Item And record_type = &apos;S&apos;)
        ///Begin
        ///	Select 0
        ///	Return 
        ///End
        ///
        ///If Exists(Select COUNT(1) From item_mst Where item = @Item And stat &lt;&gt; &apos;A&apos;)
        ///Begin
        ///	Select 0
        ///	Return 
        ///End
        ///
        ///Select 1.
        /// </summary>
        internal static string JLI_insertAvailCollec {
            get {
                return ResourceManager.GetString("JLI_insertAvailCollec", resourceCulture);
            }
        }
    }
}
