//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ue_JLI_GLPostedTransactionsExport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ue_JLI_GLPostedTransactionsExport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select
        /// led.acct As Acct
        ///,led.acct_unit1 As AcctUnit1
        ///,led.acct_unit2 As AcctUnit2
        ///,led.acct_unit3 As AcctUnit3
        ///,led.acct_unit4 As AcctUnit4
        ///,dav.AnalysisAttribute01 As AnalysisAttribute01
        ///,dav.AnalysisAttribute02 As AnalysisAttribute02
        ///,dav.AnalysisAttribute03 As AnalysisAttribute03
        ///,dav.AnalysisAttribute04 As AnalysisAttribute04
        ///,dav.AnalysisAttribute05 As AnalysisAttribute05
        ///,dav.AnalysisAttribute06 As AnalysisAttribute06
        ///,dav.AnalysisAttribute07 As AnalysisAttribute07
        ///,dav.AnalysisAttribute [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_CLM_GLPostedTransactionsExport {
            get {
                return ResourceManager.GetString("ue_JLI_CLM_GLPostedTransactionsExport", resourceCulture);
            }
        }
    }
}
