//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ue_JLI_ItemCollecAccessories.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ue_JLI_ItemCollecAccessories.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete From ue_JLI_AvailableCollection_mst Where record_type = &apos;A&apos; And item = &apos;{0}&apos;.
        /// </summary>
        internal static string ue_JLI_AvailCollDataDelete {
            get {
                return ResourceManager.GetString("ue_JLI_AvailCollDataDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare 
        ///  @Item						ItemType = &apos;{0}&apos;
        ///, @NewAssortGroups		    nvarchar(35) = &apos;{1}&apos;
        ///, @OldAssortGroups		    nvarchar(35) = &apos;{2}&apos;
        ///
        ///Declare 
        ///  @cusUf_PriceBook				ListYesNoType
        ///, @cusUf_contract_only_cust		ListYesNoType
        ///, @ShowCollection				ListYesNoType = 1
        ///, @CustNum						CustNumType
        ///
        ///
        ///DECLARE cursor_AvailCollecGroups CURSOR local static FOR
        ///	Select cust_num From ue_JLI_AvailCollecGroups_mst Where available_collec_group = &apos;Accessories&apos;
        ///OPEN cursor_AvailCollecGroups;
        ///FETCH NEXT FROM cursor_Ava [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_AvailCollDataInsertAndDelete {
            get {
                return ResourceManager.GetString("ue_JLI_AvailCollDataInsertAndDelete", resourceCulture);
            }
        }
    }
}
