//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ue_JLI_DailyOrderRecieptSummaryReport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ue_JLI_DailyOrderRecieptSummaryReport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --=============================================================================
        ///
        ///Declare @Date					nvarchar(20) = &apos;{0}&apos;
        ///
        ///DECLARE @ToEmails				nvarchar(300) = NULL
        ///      , @Subject				nvarchar(200)
        ///      , @MailMsg				nvarchar(Max)
        ///      
        ///
        ///Set @Subject = &apos;Daily Customer Order [RECEIPT] Summary for all customers : &apos; + @Date
        ///--Set @ToEmails = &apos;ushan.dalwis@jonathanlouis.net&apos;
        ///Set @ToEmails = &apos;Brandee.Reyes@jonathanlouis.com&apos;
        ///
        ///Declare @EDI_Customers nvarchar(300)
        ///Select @EDI_Customers = cp.Charfld1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_DailyOrderReceiptSummaryNotify {
            get {
                return ResourceManager.GetString("ue_JLI_DailyOrderReceiptSummaryNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--=============================================================================
        ///--=																			===
        ///--=				Submit BGTask												===
        ///--=																			===
        ///--=============================================================================
        ///
        ///Declare 
        ///  @Date					Nvarchar(15) = &apos;{0}&apos;
        ///, @CustNum			    CustNumType  = &apos;{1}&apos;
        ///
        ///
        ///
        ///DECLARE @CustExists         Int	  
        ///	  , @DocProfileExists   Int	  
        ///      , @Name               NameType
        ///
        ///DECLARE @severity           Int	  
        ///      , @taskName     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_DailyOrderRecieptSummary {
            get {
                return ResourceManager.GetString("ue_JLI_DailyOrderRecieptSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare 
        ///  @CustNum			CustNumType		= &apos;{0}&apos;
        ///, @CurrentDate		Nvarchar(15)	= &apos;{1}&apos;
        ///
        ///Declare @ResultSet Table
        ///(
        /// UbCustNum			CustNumType
        ///,UbCustName			NameType
        ///,UbCoNum 			CoNumType
        ///,UbCoLine 			CoLineType
        ///,UbCustPo 			CustPoType
        ///,UbOrderDate 		Nvarchar(15)
        ///,UbNetPrice 		Nvarchar(15)
        ///,UbShipTo 			Nvarchar(200)
        ///,UbItem 			ItemType
        ///,UbItemDesc 		DescriptionType
        ///,UbOrderQty 		Nvarchar(15)
        ///,UbItemPrice 		Nvarchar(15)
        ///,UbLTDueDate 		Nvarchar(15)
        ///,UbAccessoryDesc 	DescriptionType
        ///,UbAccessory 		It [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_Rpt_DailyOrderRecieptSummary {
            get {
                return ResourceManager.GetString("ue_JLI_Rpt_DailyOrderRecieptSummary", resourceCulture);
            }
        }
    }
}
