//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ue_JLI_DataPullingForCPQ.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ue_JLI_DataPullingForCPQ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///ip.item As Item,
        ///ip.cust_num As CustNum,
        ///ip.fabric_grade As FabricGrade,
        ///ip.price As Price
        ///FROM [dbo].[ue_JLI_CustItemFabricPrc] ip
        ///JOIN [dbo].[item_mst] im ON im.item = ip.item
        ///JOIN [dbo].[customer_mst] cu ON cu.cust_num = ip.cust_num AND cust_seq = 0
        ///WHERE CONVERT(date, effect_date) &lt;= CONVERT(date, GETDATE())
        ///AND effect_date = (
        ///	SELECT MAX(effect_date)
        ///	FROM [dbo].[ue_JLI_CustItemFabricPrc] cfp
        ///	WHERE cfp.item = ip.item And cfp.cust_num = ip.cust_num
        ///)
        ///AND ip.fabric_grade IN (&apos;Basic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_CLM_CustItemFabricPrice {
            get {
                return ResourceManager.GetString("ue_JLI_CLM_CustItemFabricPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///  ip.cust_num As CustNum
        ///, ip.item As Item
        ///, ip.fabric_grade As FabricGrade
        ///, price As Price
        ///FROM [dbo].[ue_JLI_CustItemFabricPrc] IP
        ///JOIN [dbo].[item_mst] IT ON IT.item = IP.item
        ///JOIN [dbo].[customer_mst] CU ON cu.cust_num = IP.cust_num AND cust_seq = 0
        ///WHERE CONVERT(date, effect_date) &lt;= CONVERT(date, GETDATE())
        ///AND IT.product_code IN (&apos;FGDL&apos;, &apos;FGDB&apos;, &apos;SSPW&apos;) AND CU.Uf_EDI850 = 0
        ///AND effect_date = (
        ///  SELECT MAX(effect_date)
        ///  FROM [dbo].[ue_JLI_CustItemFabricPrc] cfp
        ///  WHERE cfp.item [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_CLM_PullSwiftsellPrice {
            get {
                return ResourceManager.GetString("ue_JLI_CLM_PullSwiftsellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///   coi.site_ref     As SiteRef,
        ///   coi.co_num       As CoNum,
        ///   coi.co_line      As CoLine,
        ///   coi.co_cust_num  As CustNum,
        ///   coi.item         As Item,
        ///   coi.ship_date    As ShipDate,
        ///   coi.qty_ordered  As QtyOrdered,
        ///   coi.qty_shipped  As QtyShipped,
        ///   coi.stat         As Stat,
        ///   coi.RecordDate   As RecordDate,
        ///   coi.Uf_Cancelled As Cancelled,
        ///   coi.Uf_CancelledReason As CancelledReason,
        ///   coi.Uf_EstimatedShipDate As EstimatedShipDate,
        ///   -- JSON array of distinct, trimmed in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_CLM_SyncSytelineOrderStatus {
            get {
                return ResourceManager.GetString("ue_JLI_CLM_SyncSytelineOrderStatus", resourceCulture);
            }
        }
    }
}
