//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ue_JLI_SwatchReqTemps.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ue_JLI_SwatchReqTemps.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Declare @ResultSet Table(
        ///	 RecordType			Nchar(1)
        ///	,[partner]			nvarchar(50)
        ///	,[sword_num]		nvarchar(10)
        ///	,[sword_line]		Int
        ///	,[cust_num]			CustNumType
        ///	,[status]			NChar(1)
        ///	,[po_num]			PoNumType
        ///	,[po_date]			datetime
        ///	,[rcvd_Date]		datetime
        ///	,[ord_type]			nvarchar(2)
        ///	,[ref_num]			nvarchar(20)
        ///	,[shipto_name]		nvarchar(40)
        ///	,[shipto_addr]		nvarchar(40)
        ///	,[shipto_city]		nvarchar(40)
        ///	,[shipto_state]		nvarchar(40)
        ///	,[shipto_zip]		nvarchar(40)
        ///	,[shipto_email]		nvarchar(60)
        ///	,[qty]				int [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ue_JLI_SWLivingSpacesImport {
            get {
                return ResourceManager.GetString("ue_JLI_SWLivingSpacesImport", resourceCulture);
            }
        }
    }
}
